### ISSUE TITLE
Using an absolute path in windows causes N5Factory to try and load GoogleCloudUtils

### ISSUE THREAD

**Issue by odinsbane** [saalfeldlab/n5-universe#25]
Here is a test case.

    public static void main(String[] args){
        String localPath = "test.zarr";
        String absolutePath = Paths.get(localPath).toAbsolutePath().toString();
        System.out.println(absolutePath);
        N5Writer n5 = new N5Factory().openWriter(absolutePath);
    }

This will output:

> C:\Users\username\IdeaProjects\DeformingMesh3D-plugin\test.zarr
Exception in thread "main" java.lang.NoClassDefFoundError: org/janelia/saalfeldlab/googlecloud/GoogleCloudUtils
	at org.janelia.saalfeldlab.n5.universe.N5Factory$KeyValueAccessBackend.lambda$static$0(N5Factory.java:584)
	at org.janelia.saalfeldlab.n5.universe.N5Factory$KeyValueAccessBackend.test(N5Factory.java:618)
	at org.janelia.saalfeldlab.n5.universe.N5Factory$KeyValueAccessBackend.apply(N5Factory.java:611)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.getKeyValueAccess(N5Factory.java:243)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.openN5Container(N5Factory.java:547)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.openWriter(N5Factory.java:477)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.openN5Container(N5Factory.java:567)
	at org.janelia.saalfeldlab.n5.universe.N5Factory.openWriter(N5Factory.java:488)
	at deformablemesh.experimental.BrokenImgPlus.main(BrokenImgPlus.java:40)
Caused by: java.lang.ClassNotFoundException: org.janelia.saalfeldlab.googlecloud.GoogleCloudUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 9 more

If I use the local path the volume will be correctly created/used. Also if I use 'toUri()' I get the same exception.

**Comment by odinsbane** [comment]
I also tried using a relative path, ".\filename.zarr" and it tried to load the google cloud class.

**Comment by cmhulbert** [comment]
I'm hoping to try and test some of the windows related bugs we have seen. Could you tell me if this still happens with the most recent version of N5-Universe? Should be version `1.6.0`

**Comment by odinsbane** [comment]
1.6.0 is the same version I was using. I tried it again and I get the same error.

**Comment by cmhulbert** [comment]
So, I tried this as well, and I don't seem to have any issues with your tests case on my end. For some context, it's not incorrect that it tries to access the GoogleCloudUtils class. What's happening is that it is trying to open the container you specified ("test.zarr"), but it doesn't know what type of container it is (N5, Zarr, HDF5) or what backend it's stored at (local filesystem, AWS, google cloud). It does make some assumptions, for example based on the `.zarr` extension, but since the container doesn't exist locally, it still checks all possibilities to see if the container exists, before creating a new one, including Google Cloud. There may be some more strict heuristics we could do, but in this case that is not unexpected.

What is surprising though is that it is not able to find the class. It should be pulled in by your dependency management; it looks like you are using IntelliJ? I would make sure `n5-google-cloud` is a dependency, either with maven, or gradle if you are using them. If you have more specifics, I can try to help, but as of now I can't reproduce this, so I think it may be a build setup issue

**Comment by odinsbane** [comment]
It doesn't seem to give me the error anymore. I updated my parent pom recently so maybe that caused it to download the n5-google-cloud libs.
